### ISSUE TITLE
Review the work

### ISSUE THREAD

**Issue by ArthCodeUA** [ArthCodeUA/ssh-generator#2]
@nosovk The work of microtask [ssl-generator](https://github.com/nosovk/students-micro-tasks/blob/main/tasks/task-ssl-generator.md) has been done, unfortunately I was pushing to master directly as it is microtask and I was working solo on this. I am sorry I did not made a PR for you, please review the contents of master branch. Thank you

Artur Ladchenko IS-92

**Comment by nosovk** [comment]
Make branch production and make PR to it
